import type { Metadata } from "next";
import {
  Space_Grotesk,
  Poppins,
  Alegreya,
  Satisfy,
  Philosopher,
  Corben,
} from "next/font/google";

import "./globals.css";

// If loading a variable font, you don't need to specify the font weight
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-spacegrotesk",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poppins",
});
const alegreya = Alegreya({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-alegreya",
});
const satisfy = Corben({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-satisfy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${spaceGrotesk.variable} ${alegreya.variable} ${satisfy.variable}`}
    >
      <body className="bg-background font-sans text-foreground">
        {children}
      </body>
    </html>
  );
}
